name: Build and Publish to Azure Storage

on:
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ feature/** ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./KappelhojWeb --no-restore
    - name: Test
      run: dotnet test ./KappelhojWeb --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./KappelhojWeb --no-build 
    - uses: actions/upload-artifact@v2
      with:
        name: web-publish
        path: /KappelhojWeb/bin/Release/net5.0/publish

  Publish Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: web-publish


