name: Build and Publish to Azure Storage

on:
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ feature/** ]

jobs:
  Build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./KappelhojWeb --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./KappelhojWeb --no-build -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: web-publish
        path: ./KappelhojWeb/bin/Release/net5.0/publish/

  Deploy:
    needs: Build-and-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: web-publish
        path: web-publish
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob upload-batch --account-name kappelhojweb -d '$web' -s ./web-publish/wwwroot
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"
    # Azure logout 
    - name: logout
      run: |
            az logout


