name: Build and Publish to NameCheap

on:
  push:
    branches: [ release/web/** ]
  pull_request:
    branches: [ release/web/** ]

jobs:
  Build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Vue
      run: yarn global add @vue/cli
    - name: Vue Build
      run: yarn --cwd ./Web/main build
    - uses: actions/upload-artifact@v2
      with:
        name: web-publish
        path: ./KappelhojWeb/dist

  Deploy:
    needs: Build-and-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: web-publish
        path: web-publish
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: server286.web-hosting.com
        username: CI@kappelhoj.com
        password: ${{ secrets.ftp_password }}
        local-dir: ./web-publish/wwwroot/

    


