name: Build and Publish to Azure Storage

on:
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ feature/** ]

jobs:
  Build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release ./KappelhojWeb --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./KappelhojWeb --no-build -c Release -o /home/web
    - uses: actions/upload-artifact@v2
      with:
        name: web-publish
        path: /home/web

  Deploy:
    needs: Build-and-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: web-publish


